# Generated by Django 4.1 on 2023-11-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
