# Generated by Django 4.1 on 2023-11-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_outputimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='diffused_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='OutputImage',
        ),
    ]
